<#assign curr = entities[current_entity] />
<?php

namespace Demact\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use FOS\RestBundle\Controller\Annotations as Rest;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rest${curr.name?cap_first}Repository extends EntityRepository{

    /** 
     * GET /${curr.name?uncap_first}/{$id} 
     *  
     * @param string $userId 
     * @return Response 
     *
     * @Rest\Get("/${curr.name?uncap_first}/{$id}")
     */  
    public function get${curr.name?cap_first}Action($id)  
    {  

    }	

    /** 
     * PUT /${curr.name?uncap_first} 
     *
     * @Rest\Put("/${curr.name?uncap_first}")
     */  
    public function create${curr.name?cap_first}Action()  
    {  

    }	


    /** 
     * GET /${curr.name?uncap_first} 
     *
     * @Rest\Get("/${curr.name?uncap_first}")
     */  
    public function getAll${curr.name?cap_first}Action()  
    {  

    }	

    /** 
     * POST /${curr.name?uncap_first}/{$id} 
     *
     * @Rest\Post("/${curr.name?uncap_first}/{$id}")
     */  
    public function update${curr.name?cap_first}Action($id)  
    {  

    }	


    /** 
     * DELETE /${curr.name?uncap_first}/{$id} 
     *
     * @Rest\Delete("/${curr.name?uncap_first}/{$id}")
     */  
    public function delete${curr.name?cap_first}Action($id)  
    {  

    }	
}
