/**
 * Harmony basic views.
 * Those view or view-related classes are generated by harmony to
 * manage the base generated project. Feel free to modify them.
 */
package ${project_namespace}.harmony.view;

