<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
	
    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true" >
	    <TextView 
	        android:id="@+id/demo1_tv"
	        android:layout_width="wrap_content"
	        android:layout_height="wrap_content"
	        android:layout_marginBottom="25dp"
	        android:layout_centerHorizontal="true"
	        android:gravity="center"
	        android:textColor="@android:color/black"
	        android:text="This view has been successfully generated by harmony."/>
	    
	    <TextView
	        android:id="@+id/demo2_tv" 
	        android:layout_width="wrap_content"
	        android:layout_height="wrap_content"
	        android:layout_centerHorizontal="true"
	        android:textColor="@android:color/black"
	        android:text="You can customize it at your will."
	        android:layout_below="@id/demo1_tv"/>
	</RelativeLayout>
</RelativeLayout>
